/* product */
const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
const GET_PRODUCT_ITEM = 'GET_PRODUCT_ITEM';

const CREATE_PRODUCT = 'CREATE_PRODUCT';
const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
const DELETE_PRODUCT = 'DELETE_PRODUCT';

/* merchant */
const GET_MERCHANT_LIST = 'GET_MERCHANT_LIST';
const GET_MERCHANT_ITEM = 'GET_MERCHANT_ITEM';

const CREATE_MERCHANT = 'CREATE_MERCHANT';
const UPDATE_MERCHANT = 'UPDATE_MERCHANT';
const DELETE_MERCHANT = 'DELETE_MERCHANT';

export default {
    GET_PRODUCT_LIST,
    GET_PRODUCT_ITEM,
    CREATE_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,
    
    GET_MERCHANT_LIST,
    GET_MERCHANT_ITEM,
    CREATE_MERCHANT,
    UPDATE_MERCHANT,
    DELETE_MERCHANT
};