/* product */
export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const GET_PRODUCT_ITEM = 'GET_PRODUCT_ITEM';

export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

/* merchant */
export const GET_MERCHANT_LIST = 'GET_MERCHANT_LIST';
export const GET_MERCHANT_ITEM = 'GET_MERCHANT_ITEM';

export const CREATE_MERCHANT = 'CREATE_MERCHANT';
export const UPDATE_MERCHANT = 'UPDATE_MERCHANT';
export const DELETE_MERCHANT = 'DELETE_MERCHANT';
